In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print("Array:", arr)

Array: [1 2 3 4 5]


In [2]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("2D Array:")
print(arr)

2D Array:
[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np

arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print("3D Array:")
print(arr)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [4]:
import numpy as np

arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print("Original Array:")
print(arr)

arr[0][1][2] = 100

print("Updated Array:")
print(arr)

Original Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Updated Array:
[[[  1   2   3]
  [  4   5 100]]

 [[  7   8   9]
  [ 10  11  12]]]


In [5]:
import numpy as np
arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print("Original Array:")
print(arr)

arr[0][1][2] = 100
print("\nAfter Change:")
print(arr)

arr = np.delete(arr, 0, axis=0)
print("\nAfter Delete:")
print(arr)

Original Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

After Change:
[[[  1   2   3]
  [  4   5 100]]

 [[  7   8   9]
  [ 10  11  12]]]

After Delete:
[[[ 7  8  9]
  [10 11 12]]]


In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

print("1D Array:")
print(arr)

arr2 = arr.reshape(2, 3)

print("2D Array:")
print(arr2)

1D Array:
[1 2 3 4 5 6]
2D Array:
[[1 2 3]
 [4 5 6]]


In [7]:
import numpy as np

arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print("3D Array:")
print(arr)

arr1 = arr.flatten()

print("1D Array:")
print(arr1)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [14]:
import numpy as np
arr = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12],
     [13, 14, 15, 16]],

    [[17, 18, 19, 20],
     [21, 22, 23, 24],
     [25, 26, 27, 28],
     [29, 30, 31, 32]],

    [[33, 34, 35, 36],
     [37, 38, 39, 40],
     [41, 42, 43, 44],
     [45, 46, 47, 48]]
])



print("Shape:", arr.shape)
print("2nd Block 3rd Row:")
print(arr[1,2])

print("3rd Block 1st Column:")
print(arr[2,:,0])




Shape: (3, 4, 4)
2nd Block 3rd Row:
[25 26 27 28]
3rd Block 1st Column:
[33 37 41 45]
